services:

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - signaling-server
    restart: unless-stopped

  signaling-server:
    build: ./signaling
    restart: unless-stopped
